### PR TITLE
Add ext for linux_arm64 architecture

### LINKED ISSUE #8: envkey-fetch_X.X.X_linux_arm64 missing from `ext/`
Hello.

Now that I finally have an Apple silicon Mac, I've been experimenting with trying to get various projects running on it. For projects where we build an arm64 Ubuntu Docker container, and install the EnvKey Python package, running the project / tests fails with this stacktrace:

```
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    import envkey  # NOQA
  File "/usr/local/lib/python3.8/dist-packages/envkey/__init__.py", line 7, in <module>
    load(is_init=True)
  File "/usr/local/lib/python3.8/dist-packages/envkey/loader.py", line 26, in load
    fetch_res = fetch_env(key, cache_enabled=cache_enabled)
  File "/usr/local/lib/python3.8/dist-packages/envkey/fetch.py", line 55, in fetch_env
    res = subprocess.check_output(args).decode(encoding="utf-8").rstrip()
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/envkey/ext/envkey-fetch_1.2.9_linux_arm64/envkey-fetch'
```

I've experimented a little, and found that I can install and run `envkey-fetch` manually inside the container (presumably this installs the linux_arm64 version), but the python package doesn't use the one on the path. Obviously the easiest fix here is to include the linux_arm64 `envkey-fetch` inside `ext/` - if that's a bad idea for reasons that I'm unaware of, I'd be happy to open a PR that tries to fall back to an `envkey-fetch` executable on the path.

### PR DESCRIPTION
**Pull request by alexbaumhoer**
This PR adds an additional architecture (linux_arm64) to the `ext` directory. The contents of the directory in this PR were copied exactly from the [envkey 1.2.9 release](https://github.com/envkey/envkey-fetch/releases/tag/v1.2.9).

This allows me to install/use the `envkey-python` library within a Docker container on my M1 Mac.

Please let me know if the inclusion of this binary is not desired or if there are other more preferable solutions. The downside is this change will increase the size of the library by ~7MB but the upside is that it can be used via Docker on an Apple Silicon Mac easily!

Fixes #8

### CODE REVIEW

**Comment by sergeysolovev** [comment]
@alexbaumhoer Any news on when this will be available?

**Comment by sergeysolovev** [comment]
@alexbaumhoer This blocking me from running a docker container with python code on an M1 mac. Please let me know if there are any easy workarounds.

**Comment by danenania** [comment]
@sergeysolovev @alexbaumhoer  Sorry about the delay on this--will get it released shortly. In the meantime it looks like passing the `--platform linux/amd64` flag to `docker run` is a good workaround: https://forums.docker.com/t/run-x86-intel-and-arm-based-images-on-apple-silicon-m1-macs/117123

**Comment by danenania** [comment]
Now released in 1.3.2 -- sorry again about the delay!

**Comment by alexbaumhoer** [comment]
@danenania no worries and thank you!

**Pull request closed without merging**
